const actions={
	LOGINLOADING:"LOGINLOADING",
	LOGGEDIN:"LOGGEDIN",
	LOGGEDOUT:"LOGGEDOUT",
	SIGN_UP_LOADING:"SIGN_UP_LOADING",
	SIGNED_UP:"SIGNED_UP",
	CALL_POST:"CALL_POST",
	POST:"POST",
	CALL_FRIENDLIST:"CALL_FRIENDLIST",
	FRIENDLIST:"FRIENDLIST",
	CALL_FRIENDREQUEST:"CALL_FRIENDREQUEST",
	FRIENDREQUEST:"FRIENDREQUEST",
	SEND_FRIENDREQUEST:"SEND_FRIENDREQUEST",
	SEND_ACCEPTREQUEST:"SEND_ACCEPTREQUEST",
	ACCEPTREQUEST:"ACCEPTREQUEST",
	SEND_REJECTREQUEST:"SEND_REJECTREQUEST",
	REJECTREQUEST:"REJECTREQUEST",
	SENDING_POST:"SENDING_POST",
	POST_SENT:"POST_SENT",
	LOADING_MESSAGE :"LOADING_MESSAGE",
	MESSAGE :"MESSAGE",
	SENDING_MESSAGE :"SENDING_MESSAGE",
	MESSAGE_SENT:"MESSAGE_SENT",
	MESSAGE_CLICKED :"MESSAGE_CLICKED",
	UNCLICK:"UNCLICK"
}

export default actions;
/**************************************************************************/
